# Generated by Django 6.0.1 on 2026-03-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='correct_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='response',
            name='incorrect_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='response',
            name='skipped_count',
            field=models.IntegerField(default=0),
        ),
    ]
