# Generated by Django 6.0.1 on 2026-03-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_response_correct_count_response_incorrect_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsedetails',
            name='is_correct',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
