# Generated by Django 6.0.1 on 2026-03-20 17:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_responsedetails_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionchoice',
            name='choice_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
