# Generated by Django 6.0.1 on 2026-03-22 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_topiccomment_likes_forum_forumcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.topic'),
            preserve_default=False,
        ),
    ]
