# Generated by Django 6.0.1 on 2026-03-22 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_forum_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.topic'),
        ),
    ]
