# Generated by Django 6.0.1 on 2026-03-22 06:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_forum_topic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='forum_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forum',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='forum_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
