# Generated by Django 6.0.1 on 2026-03-23 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_forum_dislikes_forum_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.quiz'),
        ),
        migrations.AlterField(
            model_name='responsedetails',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.question'),
        ),
        migrations.AlterField(
            model_name='responsedetails',
            name='question_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.questionchoice'),
        ),
    ]
