# Generated by Django 6.0.1 on 2026-03-23 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_response_quiz_alter_responsedetails_question_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='topiccomment',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='topic_comment_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TopicSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('text', 'Matn bloki'), ('quote', 'Iqtibos'), ('keypoints', 'Asosiy nuqtalar'), ('timeline', "Vaqt chizig'i"), ('person', 'Shaxs haqida'), ('info', "Ma'lumot bloki")], max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.topic')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TopicSectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('sub_text', models.TextField(blank=True)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='courses.topicsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
