# Generated by Django 6.0.1 on 2026-03-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_topic_created_by_topic_description_topic_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='icon',
            field=models.CharField(blank=True, default='fa-book', max_length=50),
        ),
    ]
