# Generated by Django 6.0.1 on 2026-03-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_topic_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicprogress',
            name='progress',
            field=models.FloatField(default=0),
        ),
    ]
