# Generated by Django 6.0.1 on 2026-03-06 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_input', models.CharField(max_length=150, verbose_name='Email yoki Telefon Raqam')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('linked_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name="Bog'langan Foydalanuvchi")),
            ],
            options={
                'verbose_name': "Parolni Tiklash So'rovi",
                'verbose_name_plural': "Parolni Tiklash So'rovlari",
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('superadmin', 'SuperAdmin'), ('teacher', "O'qituvchi"), ('student', 'Talaba'), ('moder', 'Moder')], default='student', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('gender', models.IntegerField(blank=True, choices=[(1, 'Erkak'), (0, 'Ayol')], null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('otm', models.CharField(blank=True, max_length=100, null=True, verbose_name="Ta'lim Muassasasi")),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana")),
                ('join_date', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
