# Generated by Django 6.0 on 2025-12-15 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('superadmin', 'SuperAdmin'), ('teacher', "O'qituvchi"), ('student', 'Talaba'), ('moder', 'Moder')], default='student', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('gender', models.IntegerField(blank=True, choices=[(1, 'Erkak'), (0, 'Ayol')], null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('otm', models.CharField(blank=True, max_length=100, null=True, verbose_name="Ta'lim Muassasasi")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
