# Generated by Django 6.0.1 on 2026-03-24 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='join_date',
            new_name='date_joined',
        ),
    ]
