# Generated by Django 6.0 on 2025-12-15 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_date_of_birth_userprofile_join_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_input', models.CharField(max_length=150, verbose_name='Email yoki Telefon Raqam')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('linked_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name="Bog'langan Foydalanuvchi")),
            ],
            options={
                'verbose_name': "Parolni Tiklash So'rovi",
                'verbose_name_plural': "Parolni Tiklash So'rovlari",
            },
        ),
    ]
